// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zadatak.Data;

#nullable disable

namespace Zadatak.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508204845_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zadatak.Models.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "0611234567",
                            DateOfBirth = new DateTime(1998, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.markovic@gmail.com",
                            FullName = "Marko Markovic"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "0627654321",
                            DateOfBirth = new DateTime(1996, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jelena.ilic@gmail.com",
                            FullName = "Jelena Ilic"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "0639876543",
                            DateOfBirth = new DateTime(2000, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikola.petrovic@gmail.com",
                            FullName = "Nikola Petrovic"
                        });
                });

            modelBuilder.Entity("Zadatak.Models.Entities.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 6
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 8
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 4
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 5
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 7
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 9
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 4
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 8
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 10
                        });
                });

            modelBuilder.Entity("Zadatak.Models.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "English"
                        },
                        new
                        {
                            Id = 5,
                            Name = "React"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Problem solving"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Communication"
                        });
                });

            modelBuilder.Entity("Zadatak.Models.Entities.CandidateSkill", b =>
                {
                    b.HasOne("Zadatak.Models.Entities.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zadatak.Models.Entities.Skill", "Skillscs")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skillscs");
                });

            modelBuilder.Entity("Zadatak.Models.Entities.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("Zadatak.Models.Entities.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
